In [1]:
import numpy as np

In [2]:
x = [1,2,3.5,4.8]

In [6]:
type(x)

list

In [3]:
2*x

[1, 2, 3.5, 4.8, 1, 2, 3.5, 4.8]

In [4]:
a = np.array(x)
print(a)

[1.  2.  3.5 4.8]


In [5]:
type(a)

numpy.ndarray

In [8]:
print(a*2)

[2.  4.  7.  9.6]


In [9]:
a.dtype

dtype('float64')

In [11]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [13]:
print(x[0])
print(x[0])
print(x[0:3])

1
1
[1 3 5]


In [15]:
x = np.arange(3.2)
y = np.arange(0.1,1.2,0.1)
print(x)
print(y)


[0. 1. 2. 3.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


In [16]:
v1 = np.arange(5)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,5)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-10,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)

Creating a numpy array via arange (stop=5) : [0 1 2 3 4]

Creating a numpy array via arange (start=2,stop=5) : [2 3 4]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6 -8]



In [19]:
[[1,1],[2,2], [3,3]]

[[1, 1], [2, 2], [3, 3]]

In [22]:
b = np.array([[1,1],[2,2], [3,3]])

print(b.ndim,b.size)
print(b)

2 6
[[1 1]
 [2 2]
 [3 3]]


In [24]:
b.shape

(3, 2)

In [23]:
np.shape(b)

(3, 2)

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a = np.linspace(0, 4, 9)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [29]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.diag([1,2,3,4,-1])

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, -1]])

In [34]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [35]:
x = np.array([1, 2, 3])
np.repeat(x, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [41]:
x = np.array([1,1,2])
pdf, ebin = np.histogram(x,2)
cbin = 0.5*(ebin[1:]+ebin[:-1])

In [44]:
pdf,cbin

(array([2, 1]), array([1.25, 1.75]))

In [72]:
mat = np.random.normal(2,2.5,(4,8))
mat.shape

(4, 8)

In [73]:
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))

Overall mean of matrix is 
1.9704743108257503



In [74]:
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0))

Row mean of matrix is 
[-0.04972377  1.84050842  0.31547112  3.70775077  3.66215489  3.34980556
  0.77877249  2.159055  ]



In [75]:
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))

Column mean of matrix is 
[1.24481911 1.77027403 2.90012805 1.96667605]



In [78]:
print ('Overall varience of matrix is %s\n'%np.var(mat))

Overall varience of matrix is 5.577806997765633



In [79]:
print ('Overall standard deviation of matrix is %s\n'%np.std(mat))

Overall standard deviation of matrix is 2.361738130649889



In [80]:
print ('Overall sum of matrix is %s\n'%np.sum(mat))

Overall sum of matrix is 63.05517794642401



In [82]:
print ('Overall min of matrix is %s\n'%np.min(mat))

Overall min of matrix is -2.3126404889068155



In [83]:
print ('Overall max of matrix is %s\n'%np.max(mat))

Overall max of matrix is 6.828379134322242



In [84]:
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



In [85]:
len(dir(np))

624

# Combining Data

In [86]:
data1 = np.random.randint(5,15,size=(5,3))

In [88]:
data2 = np.random.randint(5,15,size=(5,3))

In [90]:
np.hstack([data1,data2]).shape

(5, 6)

In [91]:
np.vstack([data1, data2]).shape

(10, 3)

In [96]:
np.concatenate([data1, data2], axis=1).shape

(5, 6)

In [99]:
np.stack([data1, data2], axis=-1).shape

(5, 3, 2)

# Save and load data

In [100]:
x = np.linspace(0,5,100)
y = np.sin(x)

In [102]:
y.shape

(100,)

In [103]:
np.savetxt('x.txt',x)

In [105]:
np.savetxt('data.txt',np.c_[x,y])

In [107]:
x = np.loadtxt('x.txt')
x.shape

(100, 2)

In [109]:
# !cat x.txt

In [110]:
x = np.random.normal(0,1,(1000,1000))

In [111]:
np.savetxt('x.txt',x)

In [112]:
np.save('xdata',x)

In [114]:
x = np.load('xdata.npy')

In [115]:
x.shape

(1000, 1000)

In [116]:
x = np.random.normal(0,1,(100,100))
y = np.random.normal(0,1,(100,100))
z = np.random.normal(0,1,(100,100))

In [129]:
np.savez('dataset',x=x,y=y,z=z)

In [130]:
data = np.load('dataset.npz')

In [131]:
data.files

['x', 'y', 'z']

In [135]:
x = data['x']
y = data['y']
z = data['z']

# Questions

In [145]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# how to read CSV in python (without using any library)

In [138]:
f = open('./files/data.csv','r')

In [139]:
data0 = f.read()

In [142]:
data1 = data0.split('\n')

In [147]:
data2 = [i for i in data1 if len(i)!=0]
data2

['name,age,mark', 'ali,18,20', 'zeinab,20,19.5', 'shahin,25,16']

In [148]:
data2[0]

'name,age,mark'

In [150]:
data2[1].split(',')

['ali', '18', '20']

In [151]:
import pandas as pd

In [152]:
pd.read_csv('./files/data.csv')

name  age  mark
0     ali   18  20.0
1  zeinab   20  19.5
2  shahin   25  16.0